/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author hungh
 */
public class frm_Khachhang extends javax.swing.JPanel {

    /**
     * Creates new form khachhang
     */
    public frm_Khachhang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        panelBorder1 = new swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        myTextField1 = new swing.MyTextField();
        jLabel5 = new javax.swing.JLabel();
        myTextField5 = new swing.MyTextField();
        jLabel6 = new javax.swing.JLabel();
        myTextField6 = new swing.MyTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        myTextField2 = new swing.MyTextField();
        jLabel7 = new javax.swing.JLabel();
        myTextField7 = new swing.MyTextField();
        jLabel9 = new javax.swing.JLabel();
        myTextField8 = new swing.MyTextField();
        jLabel10 = new javax.swing.JLabel();
        myTextField9 = new swing.MyTextField();
        myButton1 = new swing.MyButton();
        myButton2 = new swing.MyButton();
        myButton3 = new swing.MyButton();
        myButton4 = new swing.MyButton();
        panelBorder2 = new swing.PanelBorder();
        panelBorder3 = new swing.PanelBorder();
        searchText1 = new swing.SearchText();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1010, 640));
        setMinimumSize(new java.awt.Dimension(1010, 640));
        setPreferredSize(new java.awt.Dimension(1010, 640));

        panelGradiente1.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente1.setColorSecundario(new java.awt.Color(255, 204, 255));

        panelBorder1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tên");
        panelBorder1.add(jLabel1);
        jLabel1.setBounds(90, 10, 210, 20);
        panelBorder1.add(myTextField1);
        myTextField1.setBounds(90, 30, 210, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tên đệm");
        panelBorder1.add(jLabel5);
        jLabel5.setBounds(90, 70, 210, 20);
        panelBorder1.add(myTextField5);
        myTextField5.setBounds(90, 90, 210, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Họ");
        panelBorder1.add(jLabel6);
        jLabel6.setBounds(90, 130, 210, 20);
        panelBorder1.add(myTextField6);
        myTextField6.setBounds(90, 150, 210, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Giới tính");
        panelBorder1.add(jLabel8);
        jLabel8.setBounds(90, 200, 48, 30);

        jRadioButton1.setBackground(new java.awt.Color(204, 204, 255));
        jRadioButton1.setText("Nữ");
        panelBorder1.add(jRadioButton1);
        jRadioButton1.setBounds(230, 200, 60, 30);

        jRadioButton2.setBackground(new java.awt.Color(204, 204, 255));
        jRadioButton2.setText("Nam");
        panelBorder1.add(jRadioButton2);
        jRadioButton2.setBounds(157, 200, 60, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ngày sinh");
        panelBorder1.add(jLabel2);
        jLabel2.setBounds(390, 10, 210, 20);
        panelBorder1.add(myTextField2);
        myTextField2.setBounds(390, 30, 210, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Số điện thoại");
        panelBorder1.add(jLabel7);
        jLabel7.setBounds(390, 70, 210, 20);
        panelBorder1.add(myTextField7);
        myTextField7.setBounds(390, 90, 210, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("E-mail");
        panelBorder1.add(jLabel9);
        jLabel9.setBounds(390, 130, 210, 20);
        panelBorder1.add(myTextField8);
        myTextField8.setBounds(390, 150, 210, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Điểm thưởng");
        panelBorder1.add(jLabel10);
        jLabel10.setBounds(390, 190, 210, 20);
        panelBorder1.add(myTextField9);
        myTextField9.setBounds(390, 210, 210, 30);

        myButton1.setBackground(new java.awt.Color(125, 224, 237));
        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        myButton1.setText("Hiển thị");
        myButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBorder1.add(myButton1);
        myButton1.setBounds(660, 50, 120, 33);

        myButton2.setBackground(new java.awt.Color(125, 224, 237));
        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        myButton2.setText("Thêm");
        myButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        panelBorder1.add(myButton2);
        myButton2.setBounds(820, 50, 120, 33);

        myButton3.setBackground(new java.awt.Color(125, 224, 237));
        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/floppy-disk.png"))); // NOI18N
        myButton3.setText("Cập nhật");
        myButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBorder1.add(myButton3);
        myButton3.setBounds(660, 130, 120, 33);

        myButton4.setBackground(new java.awt.Color(125, 224, 237));
        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tay.png"))); // NOI18N
        myButton4.setText("Xóa");
        myButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBorder1.add(myButton4);
        myButton4.setBounds(830, 130, 120, 33);

        panelGradiente1.add(panelBorder1);
        panelBorder1.setBounds(10, 0, 990, 260);

        panelBorder2.setBackground(new java.awt.Color(204, 204, 255));

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder3.add(searchText1);
        searchText1.setBounds(10, 0, 220, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_24px.png"))); // NOI18N
        panelBorder3.add(jLabel3);
        jLabel3.setBounds(240, 0, 40, 40);

        panelBorder2.add(panelBorder3);
        panelBorder3.setBounds(640, 10, 280, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        panelBorder2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 990, 300);

        panelGradiente1.add(panelBorder2);
        panelBorder2.setBounds(10, 270, 990, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private swing.MyButton myButton1;
    private swing.MyButton myButton2;
    private swing.MyButton myButton3;
    private swing.MyButton myButton4;
    private swing.MyTextField myTextField1;
    private swing.MyTextField myTextField2;
    private swing.MyTextField myTextField5;
    private swing.MyTextField myTextField6;
    private swing.MyTextField myTextField7;
    private swing.MyTextField myTextField8;
    private swing.MyTextField myTextField9;
    private swing.PanelBorder panelBorder1;
    private swing.PanelBorder panelBorder2;
    private swing.PanelBorder panelBorder3;
    private swing.PanelGradiente panelGradiente1;
    private swing.SearchText searchText1;
    // End of variables declaration//GEN-END:variables
}
