/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author hungh
 */
public class frm_Sanpham extends javax.swing.JPanel {

    /**
     * Creates new form sanpham
     */
    public frm_Sanpham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        panelBorder1 = new swing.PanelBorder();
        myTextField1 = new swing.MyTextField();
        jLabel1 = new javax.swing.JLabel();
        myTextField2 = new swing.MyTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        myTextField9 = new swing.MyTextField();
        jLabel9 = new javax.swing.JLabel();
        myTextField10 = new swing.MyTextField();
        jLabel10 = new javax.swing.JLabel();
        myTextField11 = new swing.MyTextField();
        jLabel11 = new javax.swing.JLabel();
        myTextField12 = new swing.MyTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        myButton2 = new swing.MyButton();
        myButton3 = new swing.MyButton();
        myButton4 = new swing.MyButton();
        myButton5 = new swing.MyButton();
        panelBorder2 = new swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelBorder3 = new swing.PanelBorder();
        searchText1 = new swing.SearchText();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1010, 640));

        panelGradiente1.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente1.setColorSecundario(new java.awt.Color(255, 204, 255));

        panelBorder1.setBackground(new java.awt.Color(204, 204, 255));
        panelBorder1.add(myTextField1);
        myTextField1.setBounds(30, 30, 210, 40);

        jLabel1.setText("Mã sản phẩm");
        panelBorder1.add(jLabel1);
        jLabel1.setBounds(30, 10, 210, 20);
        panelBorder1.add(myTextField2);
        myTextField2.setBounds(30, 100, 210, 40);

        jLabel2.setText("Tên sản phẩm");
        panelBorder1.add(jLabel2);
        jLabel2.setBounds(30, 80, 210, 20);

        jLabel3.setText("Nhà sản xuất");
        panelBorder1.add(jLabel3);
        jLabel3.setBounds(30, 150, 210, 20);

        jLabel4.setText("Màu sắc");
        panelBorder1.add(jLabel4);
        jLabel4.setBounds(30, 220, 210, 20);

        jLabel5.setText("Danh mục");
        panelBorder1.add(jLabel5);
        jLabel5.setBounds(280, 10, 210, 20);

        jLabel6.setText("Size");
        panelBorder1.add(jLabel6);
        jLabel6.setBounds(280, 80, 210, 20);

        jLabel7.setText("Chất liệu");
        panelBorder1.add(jLabel7);
        jLabel7.setBounds(280, 150, 210, 20);

        jLabel8.setText("Thương hiệu");
        panelBorder1.add(jLabel8);
        jLabel8.setBounds(280, 220, 210, 20);
        panelBorder1.add(myTextField9);
        myTextField9.setBounds(530, 30, 210, 40);

        jLabel9.setText("Khuyến mãi");
        panelBorder1.add(jLabel9);
        jLabel9.setBounds(530, 10, 210, 20);
        panelBorder1.add(myTextField10);
        myTextField10.setBounds(530, 100, 210, 40);

        jLabel10.setText("Số lượng tồn");
        panelBorder1.add(jLabel10);
        jLabel10.setBounds(530, 80, 210, 20);
        panelBorder1.add(myTextField11);
        myTextField11.setBounds(530, 170, 210, 40);

        jLabel11.setText("Giá nhập");
        panelBorder1.add(jLabel11);
        jLabel11.setBounds(530, 150, 210, 20);
        panelBorder1.add(myTextField12);
        myTextField12.setBounds(530, 240, 210, 40);

        jLabel12.setText("Mô tả");
        panelBorder1.add(jLabel12);
        jLabel12.setBounds(760, 220, 220, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(2);
        jTextArea1.setTabSize(0);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jScrollPane4.setViewportView(jTextArea1);

        panelBorder1.add(jScrollPane4);
        jScrollPane4.setBounds(760, 240, 220, 70);

        jLabel13.setText("Giá bán");
        panelBorder1.add(jLabel13);
        jLabel13.setBounds(530, 220, 210, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        panelBorder1.add(jComboBox1);
        jComboBox1.setBounds(280, 240, 210, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        panelBorder1.add(jComboBox2);
        jComboBox2.setBounds(30, 170, 210, 40);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        panelBorder1.add(jComboBox3);
        jComboBox3.setBounds(30, 240, 210, 40);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        panelBorder1.add(jComboBox4);
        jComboBox4.setBounds(280, 30, 210, 40);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        panelBorder1.add(jComboBox5);
        jComboBox5.setBounds(280, 100, 210, 40);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        panelBorder1.add(jComboBox6);
        jComboBox6.setBounds(280, 170, 210, 40);

        myButton2.setBackground(new java.awt.Color(125, 224, 237));
        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/floppy-disk.png"))); // NOI18N
        myButton2.setText("Cập nhật");
        myButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBorder1.add(myButton2);
        myButton2.setBounds(810, 120, 130, 40);

        myButton3.setBackground(new java.awt.Color(125, 224, 237));
        myButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        myButton3.setText("Làm mới");
        myButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBorder1.add(myButton3);
        myButton3.setBounds(810, 20, 130, 40);

        myButton4.setBackground(new java.awt.Color(125, 224, 237));
        myButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tay.png"))); // NOI18N
        myButton4.setText("Xóa");
        myButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBorder1.add(myButton4);
        myButton4.setBounds(810, 170, 130, 40);

        myButton5.setBackground(new java.awt.Color(125, 224, 237));
        myButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        myButton5.setText("Thêm");
        myButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        panelBorder1.add(myButton5);
        myButton5.setBounds(810, 70, 130, 40);

        panelGradiente1.add(panelBorder1);
        panelBorder1.setBounds(8, 0, 990, 320);

        panelBorder2.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        panelBorder2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 990, 240);

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder3.add(searchText1);
        searchText1.setBounds(10, 0, 250, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_24px.png"))); // NOI18N
        panelBorder3.add(jLabel14);
        jLabel14.setBounds(270, 0, 24, 40);

        panelBorder2.add(panelBorder3);
        panelBorder3.setBounds(660, 10, 310, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-page.png"))); // NOI18N
        jLabel15.setText("Thêm thuộc tính");
        panelBorder2.add(jLabel15);
        jLabel15.setBounds(260, 10, 180, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hide.png"))); // NOI18N
        jLabel16.setText("  Hiện sản phẩm ẩn");
        panelBorder2.add(jLabel16);
        jLabel16.setBounds(40, 10, 180, 40);

        panelGradiente1.add(panelBorder2);
        panelBorder2.setBounds(10, 329, 990, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private swing.MyButton myButton2;
    private swing.MyButton myButton3;
    private swing.MyButton myButton4;
    private swing.MyButton myButton5;
    private swing.MyTextField myTextField1;
    private swing.MyTextField myTextField10;
    private swing.MyTextField myTextField11;
    private swing.MyTextField myTextField12;
    private swing.MyTextField myTextField2;
    private swing.MyTextField myTextField9;
    private swing.PanelBorder panelBorder1;
    private swing.PanelBorder panelBorder2;
    private swing.PanelBorder panelBorder3;
    private swing.PanelGradiente panelGradiente1;
    private swing.SearchText searchText1;
    // End of variables declaration//GEN-END:variables
}
