/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author hungh
 */
public class FrmBanhang extends javax.swing.JPanel {

    /**
     * Creates new form banhang
     */
    public FrmBanhang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        searchText1 = new swing.SearchText();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        myButton3 = new swing.MyButton();
        panelGradiente2 = new swing.PanelGradiente();
        myButton1 = new swing.MyButton();
        myButton2 = new swing.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        panelGradiente3 = new swing.PanelGradiente();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        myButton4 = new swing.MyButton();
        myButton5 = new swing.MyButton();
        panelGradiente4 = new swing.PanelGradiente();
        jLabel5 = new javax.swing.JLabel();
        myTextField1 = new swing.MyTextField();
        jLabel7 = new javax.swing.JLabel();
        myTextField2 = new swing.MyTextField();
        jLabel8 = new javax.swing.JLabel();
        myTextField3 = new swing.MyTextField();
        jLabel9 = new javax.swing.JLabel();
        myTextField4 = new swing.MyTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        myTextField5 = new swing.MyTextField();
        jLabel12 = new javax.swing.JLabel();
        myTextField6 = new swing.MyTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        myButton6 = new swing.MyButton();
        myButton7 = new swing.MyButton();
        myButton8 = new swing.MyButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setMinimumSize(new java.awt.Dimension(1010, 640));
        setName(""); // NOI18N

        panelGradiente1.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente1.setColorSecundario(new java.awt.Color(255, 204, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(20);
        jScrollPane2.setViewportView(jTable2);

        panelGradiente1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 560, 190);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Sản phẩm");
        panelGradiente1.add(jLabel1);
        jLabel1.setBounds(0, 0, 100, 15);
        panelGradiente1.add(searchText1);
        searchText1.setBounds(20, 20, 200, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_24px.png"))); // NOI18N
        panelGradiente1.add(jLabel3);
        jLabel3.setBounds(220, 20, 30, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelGradiente1.add(jComboBox1);
        jComboBox1.setBounds(270, 20, 200, 30);

        myButton3.setBackground(new java.awt.Color(125, 224, 237));
        myButton3.setText("Lọc");
        panelGradiente1.add(myButton3);
        myButton3.setBounds(490, 20, 70, 30);

        panelGradiente2.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente2.setColorSecundario(new java.awt.Color(255, 204, 255));

        myButton1.setBackground(new java.awt.Color(125, 224, 237));
        myButton1.setText("Xóa");
        panelGradiente2.add(myButton1);
        myButton1.setBounds(500, 50, 70, 30);

        myButton2.setBackground(new java.awt.Color(125, 224, 237));
        myButton2.setText("Clear");
        panelGradiente2.add(myButton2);
        myButton2.setBounds(500, 100, 70, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Giỏ hàng");
        panelGradiente2.add(jLabel2);
        jLabel2.setBounds(0, 0, 55, 15);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowHeight(20);
        jScrollPane3.setViewportView(jTable3);

        panelGradiente2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 470, 150);

        panelGradiente3.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente3.setColorSecundario(new java.awt.Color(255, 204, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        panelGradiente3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 460, 150);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Hóa đơn chờ");
        jLabel4.setToolTipText("");
        panelGradiente3.add(jLabel4);
        jLabel4.setBounds(0, 0, 90, 15);

        myButton4.setBackground(new java.awt.Color(125, 224, 237));
        myButton4.setText("Tạo hóa đơn");
        panelGradiente3.add(myButton4);
        myButton4.setBounds(482, 50, 93, 30);

        myButton5.setBackground(new java.awt.Color(125, 224, 237));
        myButton5.setText("Hủy");
        panelGradiente3.add(myButton5);
        myButton5.setBounds(485, 100, 90, 30);

        panelGradiente4.setColorPrimario(new java.awt.Color(204, 255, 255));
        panelGradiente4.setColorSecundario(new java.awt.Color(255, 204, 255));
        panelGradiente4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Thanh toán");
        jLabel5.setToolTipText("");
        panelGradiente4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, -1));
        panelGradiente4.add(myTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 250, 30));

        jLabel7.setText("Tên khách hàng");
        panelGradiente4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 250, 20));
        panelGradiente4.add(myTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 250, 30));

        jLabel8.setText("SĐT khách hàng");
        panelGradiente4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, 20));
        panelGradiente4.add(myTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 30));

        jLabel9.setText("Điểm thưởng");
        panelGradiente4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 250, 20));
        panelGradiente4.add(myTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 250, 30));

        jLabel10.setText("Hình thức thanh toán");
        panelGradiente4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        panelGradiente4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 250, 30));

        jLabel11.setText("Tổng tiền");
        panelGradiente4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, 20));
        panelGradiente4.add(myTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 250, 30));

        jLabel12.setText("Tiền khách đưa");
        panelGradiente4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 250, 20));
        panelGradiente4.add(myTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 250, 30));

        jLabel13.setText("Ghi chú");
        panelGradiente4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 250, 20));

        jLabel14.setText("Tiền thừa");
        panelGradiente4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 250, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(3);
        jTextArea1.setTabSize(0);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jScrollPane4.setViewportView(jTextArea1);
        jTextArea1.getAccessibleContext().setAccessibleDescription("");

        panelGradiente4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 250, 60));

        jCheckBox1.setBackground(new java.awt.Color(255, 204, 255));
        jCheckBox1.setText("In hóa đơn");
        panelGradiente4.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 100, -1));

        myButton6.setBackground(new java.awt.Color(125, 224, 237));
        myButton6.setForeground(new java.awt.Color(0, 51, 102));
        myButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/credit-card.png"))); // NOI18N
        myButton6.setText("Thanh toán");
        myButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        panelGradiente4.add(myButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 250, 40));

        myButton7.setBackground(new java.awt.Color(125, 224, 237));
        myButton7.setText("Xác nhận");
        panelGradiente4.add(myButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 90, 30));

        myButton8.setBackground(new java.awt.Color(125, 224, 237));
        myButton8.setText("Sử dụng");
        panelGradiente4.add(myButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGradiente3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGradiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(panelGradiente4, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelGradiente3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelGradiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelGradiente4, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private swing.MyButton myButton1;
    private swing.MyButton myButton2;
    private swing.MyButton myButton3;
    private swing.MyButton myButton4;
    private swing.MyButton myButton5;
    private swing.MyButton myButton6;
    private swing.MyButton myButton7;
    private swing.MyButton myButton8;
    private swing.MyTextField myTextField1;
    private swing.MyTextField myTextField2;
    private swing.MyTextField myTextField3;
    private swing.MyTextField myTextField4;
    private swing.MyTextField myTextField5;
    private swing.MyTextField myTextField6;
    private swing.PanelGradiente panelGradiente1;
    private swing.PanelGradiente panelGradiente2;
    private swing.PanelGradiente panelGradiente3;
    private swing.PanelGradiente panelGradiente4;
    private swing.SearchText searchText1;
    // End of variables declaration//GEN-END:variables
}
